trigger:
- main

pool:
  vmImage: windows-2022

steps:
- script: Perform publish
  displayName: 'Perform publish as specified'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "About to install..."
      dotnet new tool-manifest
      dotnet nuget add source -n Sitecore https://nuget.sitecore.com/resources/v3/index.json
      dotnet tool install Sitecore.CLI   
      Write-Host "Completed installation..."