trigger:
- main

pool:
  vmImage: windows-2022

schedules:
- cron: "00 16 10 6 * "
  displayName: Publish today at 16:00 PM UTC,
  branches:
    include:
    - main
  always: true

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "About to publish"
      dotnet sitecore login --authority  https://auth.sitecorecloud.io --cm $(instance-url) --audience https://api.sitecorecloud.io --allow-write true --client-credentials true --client-id $(client-id) --client-secret $(client-secret)
      dotnet sitecore publish --environment-name default item --path "/sitecore/content/Demo Headless Site Collection Folder/Demo Site Collection/Demo Site/Home"
      Write-Host "Publish completed"